### ISSUE TITLE
MERL Harvested is always 0

### ISSUE THREAD

**Issue by linaspasv** [scv-finance/portfolio#6]
Hello, MERL harvested is always 0 in merlinlab.com CAKE vault.

![image](https://user-images.githubusercontent.com/1407067/123312689-57ea0380-d531-11eb-95ed-3cc1d2271092.png)

**Comment by rjyo** [comment]
Thanks for reporting. Please share the last 4 digits of your address and let us know whether you're a Pro member.

**Comment by rjyo** [comment]
We may have found the problem and fixed it. @linaspasv Let us know whether it's OK on your side.

**Comment by linaspasv** [comment]
Hi @rjyo , I am not a Pro member. The problem fixed for me. Thank you. :-)
