### ISSUE TITLE
BSC TENFI Cake field is not accounted towards Daily Earn

### ISSUE THREAD

**Issue by linaspasv** [scv-finance/portfolio#8]
**Describe the bug**

It looks like Farm APY for Cake in TENFI is not accounted towards Daily Earn. I am receiving around 1 CAKE / day + TENFI tokens and that's around ~15-17 USD daily but total Daily Earn estimation is around 5 USD. Also total APY is too small, as all the farms listed in SCV has over 100% but displayed is 37% only.

**To Reproduce**
- Last 4 digits of wallet: dCDF
- Membership: Pro

**Comment by rjyo** [comment]
Thanks for the report. Please try to refresh and check the numbers.

**Comment by linaspasv** [comment]
@rjyo looks better now. Thank you.

p.s. it would be very helpful to see an approx estimate of daily earnings per individual pool.

**Comment by rjyo** [comment]
Thanks for the advice!
